// <auto-generated />
using System;
using LizzardPirates.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LizzardPirates.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LizzardPirates.Models.LizzardPirate", b =>
                {
                    b.Property<int>("LizzardPirateId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("LizzardType")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("PirateRole")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("LizzardPirateId");

                    b.ToTable("LizzardCrew");
                });
#pragma warning restore 612, 618
        }
    }
}
